require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'JSIPeformance' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
     :hermes_enabled => false
  )
 

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  # ML pods
  pod 'GoogleMLKit/TextRecognition','2.2.0'
  pod 'DeviceKit', '~> 2.0'



  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'FaceDetectorMLKit'
  ]

  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    'BarcodeDetectorMLKit'
  ]



end
